version: "3.9"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on:
      database:
        condition: service_healthy
    restart: on-failure
    networks:
      - backend_network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "8081:80"
    env_file:
      - ./frontend/.env
    depends_on:
      backend:
        condition: service_started
    restart: on-failure
    networks:
      - backend_network
    
  database:
    container_name: database
    image: postgres:12
    env_file:
      - ./backend/.env
    volumes:
      - ./pg-data:/var/lib/postgresql/data/pgdata 
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U student -d kupipodariday" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge